import Link from "next/link";
import { ArrowRight, ArrowUpRight, Headphones, LampDesk, Cable, Backpack } from "lucide-react";
import { getBanners, getCategories, getProducts } from "@/lib/api";
import { Hero } from "@/components/hero";
import { Benefits } from "@/components/benefits";
import { ProductCard } from "@/components/product-card";
import { ProductPhoto } from "@/components/product-photo";

export const dynamic = "force-dynamic";
export const metadata = { alternates: { canonical: "/" } };

export default async function Home() {
  const [banners, categories, featured, arrivals, bestsellers] = await Promise.allSettled([getBanners(), getCategories(), getProducts(new URLSearchParams({featured: "1"})), getProducts(new URLSearchParams({new: "1", sort: "newest"})), getProducts(new URLSearchParams({sort: "bestselling"}))]);
  const categoryIcons = [Headphones, LampDesk, Cable, Backpack];
  const categoryNotes = ["Find your soundtrack", "Make yourself at home", "A smarter everyday", "Ready for wherever"];
  return <><div className="container home-start"><Hero banners={banners.status === "fulfilled" ? banners.value.data.filter(b => b.position === "hero" || b.position === "home" || b.position === "homepage") : []}/></div><Benefits/>
    <section className="section container"><div className="section-heading"><div><p className="eyebrow">FIND YOUR KIND OF GOOD</p><h2>Made for your everyday</h2></div><Link className="text-link" href="/shop">Explore all <ArrowUpRight size={17}/></Link></div><div className="category-grid">{categories.status === "fulfilled" ? categories.value.data.map((category, index) => { const Icon = categoryIcons[index % categoryIcons.length]; return <Link href={`/shop?category=${category.slug}`} className={`category-card category-${index % 4}`} key={category.id}><div className="category-icon"><Icon size={37} strokeWidth={1.25}/></div><div><h3>{category.name}</h3><p>{categoryNotes[index % 4]}</p></div><ArrowUpRight size={19}/></Link>; }) : <p className="service-message">Our collection is taking a moment to load. <Link href="/shop">Try the shop again.</Link></p>}</div></section>
    <section className="section container"><div className="section-heading"><div><p className="eyebrow">THE SHORTLIST</p><h2>Good things. Great picks.</h2><p>Our current favourites, ready to become yours.</p></div><Link className="text-link" href="/shop?featured=1">Shop the edit <ArrowUpRight size={17}/></Link></div>{featured.status === "fulfilled" && featured.value.data.length ? <div className="product-grid">{featured.value.data.slice(0, 4).map(product => <ProductCard key={product.id} product={product}/>)}</div> : <div className="empty-state compact"><h3>A new collection is on its way.</h3><p>Please check back soon, or browse all available products.</p><Link href="/shop" className="text-link">Browse the shop <ArrowRight size={16}/></Link></div>}</section>
    <section className="container editorial-wrap"><div className="editorial"><div className="editorial-image"><ProductPhoto src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop&q=85" alt="Coffee and considered details for a slower morning" sizes="(max-width: 720px) 100vw, 50vw"/></div><div className="editorial-copy"><p className="eyebrow">MAKE ROOM FOR THE LITTLE THINGS</p><h2>A better morning.<br/>A calmer corner.<br/><em>A space that’s yours.</em></h2><p>Small details have a way of changing the whole day. Bring a little more thought into your home.</p><Link href="/shop?category=home-living" className="button button-white">Discover home & living <ArrowUpRight size={18}/></Link></div></div></section>
    {arrivals.status === "fulfilled" && arrivals.value.data.length > 0 && <section className="section container"><div className="section-heading"><div><p className="eyebrow">FRESH FINDS</p><h2>A little something new</h2><p>New arrivals with a place in your everyday.</p></div><Link className="text-link" href="/shop?new=1">See what’s new <ArrowUpRight size={17}/></Link></div><div className="product-grid">{arrivals.value.data.slice(0,4).map(product => <ProductCard key={product.id} product={product}/>)}</div></section>}
    {bestsellers.status === "fulfilled" && bestsellers.value.data.length > 0 && <section className="section container bestseller-section"><div className="section-heading"><div><p className="eyebrow">EXPLORE THE COLLECTION</p><h2>Worth a closer look</h2><p>Browse the collection, ordered by completed purchases.</p></div><Link className="text-link" href="/shop?sort=bestselling">Shop best sellers <ArrowUpRight size={17}/></Link></div><div className="product-grid">{bestsellers.value.data.slice(0,4).map(product => <ProductCard key={product.id} product={product}/>)}</div></section>}
    <section className="closing-note container"><span className="small-star">✳</span><h2>Less searching.<br/>More <em>finding your thing.</em></h2><Link href="/shop" className="button button-dark">Meet the collection <ArrowUpRight size={18}/></Link></section>
  </>;
}
